keepmgr_address = "rome.sev.lab.enarx.dev"
keepmgr_port = 3030
wasmldr_address = "rome.sev.lab.enarx.dev"
wasmldr_port = 3040
workload_path = "external/return_1.wasm"
#workload_path = "external/echo-server.wasm"
workload_dir = "external"
nil = false
kvm = false
sev = true
sgx = false
#TODO - this needs to be versioned
#NOTE - get this from the running enarx-keepldr thus: 
#     - `ENARX_BACKEND=sev cargo run report /home/mikecamel/programming/enarx-project/enarx-wasmldr/target
#        /x86_64-unknown-linux-musl/release/enarx-wasmldr` 
sev-digest = [221, 35, 238, 3, 93, 185, 127, 99, 74, 109, 153, 25, 249, 41, 141, 250, 17, 104, 15, 125, 170, 122, 116, 141, 57, 54, 15, 101, 245, 58, 230, 72]
