keepmgr_address = "rome.sev.lab.enarx.dev"
keepmgr_port = 3030
wasmldr_address = "rome.sev.lab.enarx.dev"
wasmldr_port = 3040
workload_path = "external/return_1.wasm"
#workload_path = "external/echo-server.wasm"
workload_dir = "external"
nil = false
kvm = false
sev = true
sgx = false
#TODO - this needs to be versioned
#NOTE - get this from the running enarx-keepldr thus: 
#     - `ENARX_BACKEND=sev cargo run report /home/mikecamel/programming/enarx-project/enarx-wasmldr/target
#        /x86_64-unknown-linux-musl/release/enarx-wasmldr` 
sev-digest = [57, 15, 242, 34, 40, 255, 109, 130, 37, 246, 251, 233, 0, 37, 156, 180, 230, 243, 38, 95, 163, 67, 178, 8, 219, 35, 88, 134, 202, 184, 89, 238]