keepmgr_address = "rome.sev.lab.enarx.dev"
keepmgr_port = 3030
wasmldr_address = "rome.sev.lab.enarx.dev"
wasmldr_port = 3040
workload_path = "external/return_1.wasm"
#workload_path = "external/echo-server.wasm"
workload_dir = "external"
nil = false
kvm = false
sev = true
sgx = false
#TODO - this needs to be versioned
#NOTE - get this from the running enarx-keepldr thus: 
#     - `ENARX_BACKEND=sev cargo run report /home/mikecamel/programming/enarx-project/enarx-wasmldr/target
#        /x86_64-unknown-linux-musl/release/enarx-wasmldr` 
#from working set (20210118)
#sev-digest = [128, 61, 169, 82, 20, 221, 15, 80, 33, 216, 145, 169, 14, 164, 13, 238, 122, 237, 233, 205, 208, 79, 205, 40, 239, 165, 147, 128, 81, 68, 142, 194]
sev-digest = [204, 20, 33, 134, 29, 100, 190, 129, 167, 124, 38, 141, 193, 32, 165, 111, 229, 189, 108, 21, 223, 236, 91, 241, 219, 11, 143, 158, 24, 176, 232, 223]
sgx-digest = []
sgx-trusted-public-key-chain = "";