keepmgr_address = "rome.sev.lab.enarx.dev"
keepmgr_port = 3030
wasmldr_address = "rome.sev.lab.enarx.dev"
wasmldr_port = 3040
workload_path = "external/return_1.wasm"
workload_dir = "external"
nil = false
kvm = false
sev = true
sgx = false
#TODO - this needs to be versioned
#NOTE - get this from the running enarx-keepldr thus: 
#     - `ENARX_BACKEND=sev cargo run report /home/mikecamel/programming/enarx-project/enarx-wasmldr/target
#        /x86_64-unknown-linux-musl/debug/enarx-wasmldr` 
sev-digest = [249, 151, 186, 148, 12, 214, 235, 185, 219, 210, 112, 110, 80, 44, 0, 82, 198, 248, 41, 240, 46, 222, 249, 23, 63, 236, 81, 93, 231, 89, 44, 11]