keepmgr_address = "rome.sev.lab.enarx.dev"
keepmgr_port = 3030
wasmldr_address = "rome.sev.lab.enarx.dev"
wasmldr_port = 3040
workload_path = "external/return_1.wasm"
#workload_path = "external/echo-server.wasm"
workload_dir = "external"
nil = false
kvm = false
sev = true
sgx = false
#TODO - this needs to be versioned
#NOTE - get this from the running enarx-keepldr thus: 
#     - `ENARX_BACKEND=sev cargo run report /home/mikecamel/programming/enarx-project/enarx-wasmldr/target
#        /x86_64-unknown-linux-musl/release/enarx-wasmldr` 
sev-digest = [77, 217, 155, 196, 131, 188, 38, 36, 174, 73, 176, 160, 17, 122, 165, 97, 234, 64, 248, 3, 141, 3, 162, 106, 179, 44, 20, 40, 125, 95, 177, 104]